apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: hme-kube-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.2.2-10.0.2.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hme-kube-advrt
  namespace: metallb-system
