apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hme
  name: dashy-pv-claim
  labels:
    app: dashy
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi