apiVersion: v1
kind: Service
metadata:
  namespace: hme
  name: doc
  labels:
    app: doc
spec:
  ports:
    - port: 8080
      name: dillinger
    - port: 80
      name: bookstack
  selector:
    app: doc
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hme
  name: dill-pv-claim
  labels:
    app: doc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hme
  name: bookstack-pv-claim
  labels:
    app: doc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc
  namespace: hme
  labels:
    app: doc
    tier: frontend
spec:
  selector:
    matchLabels:
      app: doc
      tier: frontend
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: doc
        tier: frontend
    spec:
      containers:
        - image: lscr.io/linuxserver/dillinger
          name: dillinger
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - containerPort: 8080
              name: dillinger
          volumeMounts:
            - name: dillinger-persistent-storage
              mountPath: /config
        - image: linuxserver/bookstack
          name: bookstack
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
            - name: APP_URL
              value: http://bookstack.yawmzero.io
            - name: DB_USER
              value: hme-db
            - name: DB_DATABASE
              value: bookstack
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: postgres1.yawmzero.io
            - name: DB_PASS
              value: WmF74ABXvE
              # valueFrom:
              #   secretKeyRef:
              #     name: postgresql
              #     key: password
          ports:
            - containerPort: 80
              name: bookstack
          volumeMounts:
            - name: bookstack-persistent-storage
              mountPath: /config
      volumes:
        - name: bookstack-persistent-storage
          persistentVolumeClaim:
            claimName: bookstack-pv-claim
        - name: dillinger-persistent-storage
          persistentVolumeClaim:
            claimName: dill-pv-claim

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: doc
  namespace: hme
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`dillinger.yawmzero.io`)
    kind: Rule
    services:
    - name: doc
      port: 8080
  - match: Host(`bookstack.yawmzero.io`)
    kind: Rule
    services:
    - name: doc
      port: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#   labels:
#     app: doc
#   name: doc
#   namespace: hme
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: dillinger.yawmzero.io
#       http:
#         paths:
#           - backend:
#               service:
#                 name: doc
#                 port:
#                   number: 8080
#             path: /
#             pathType: ImplementationSpecific
#     - host: bookstack.yawmzero.io
#       http:
#         paths:
#           - backend:
#               service:
#                 name: doc
#                 port:
#                   number: 80
#             path: /
#             pathType: ImplementationSpecific
#   tls:
#     - hosts:
#         - dillinger.yawmzero.io
#         - bookstack.yawmzero.io
#       secretName: tls-traefik
# status:
#   loadBalancer: {}